# Site wide configuration

title: DUM
locale: en_US
description: We Are DUM
logo: 
search: true
url: http://www.dum.land
# Jekyll configuration

permalink:   /:categories/:title/


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: John McCartin
  email: john.mccartin@gmail.com
